[env:esp_wrover_kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino

monitor_speed = 115200
monitor_eol = LF

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++14
    -Wall
    -O2
    -Ilib/mip_sdk/src/cpp
    -DMICROSTRAIN_PLATFORM_EMBEDDED=1
    -DMICROSTRAIN_TIMESTAMP_TYPE=uint32_t
    -DMICROSTRAIN_LOGGING_MAX_LEVEL=MICROSTRAIN_LOGGING_LEVEL_WARN_
    -DMIP_LOGGING_MAX_LEVEL=MICROSTRAIN_LOGGING_LEVEL_WARN_
    -DMIP_ENABLE_METADATA=0
    -DMIP_ENABLE_EXTRAS=0
    -DMICROSTRAIN_ENABLE_EXTRAS=0

lib_ldf_mode = deep+
