#!/usr/bin/env python3
"""
Plot CV7 EKF/GPS CSV output with matplotlib.

This script reads EKF and GPS CSV files generated by CV7_INS_EKF.py, then opens
interactive 2D and 3D plots. It does not save image files.

Both EKF and GPS tracks are drawn as points. Point counts are printed to the
console and shown in the plot titles.
"""

from __future__ import annotations

import argparse
import csv
import glob
import math
import os
from dataclasses import dataclass
from typing import Iterable, List, Optional

try:
    import matplotlib.pyplot as plt
except ImportError as exc:
    raise SystemExit("matplotlib is required. Install it with: python -m pip install matplotlib") from exc


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
EARTH_RADIUS_M = 6378137.0
IMU_EKF_COLOR = "#1f77b4"
GPS_RAW_COLOR = "#ff7f0e"
START_EDGE_COLOR = "black"


@dataclass
class TrackPoint:
    lat_deg: float
    lon_deg: float
    height_m: float
    time_s: Optional[float] = None


@dataclass
class LocalPoint:
    east_m: float
    north_m: float
    height_m: float
    time_s: Optional[float] = None


def parse_float(value: object) -> Optional[float]:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        number = float(text)
    except ValueError:
        return None
    if not math.isfinite(number):
        return None
    return number


def is_truthy_csv(value: object) -> bool:
    text = str(value or "").strip().lower()
    return text in {"1", "true", "yes", "y"}


def read_track_csv(path: Optional[str], require_position_valid: bool) -> List[TrackPoint]:
    points: List[TrackPoint] = []
    if not path or not os.path.exists(path):
        return points

    with open(path, "r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            if require_position_valid and "position_valid" in row:
                if not is_truthy_csv(row.get("position_valid")):
                    continue

            lat = parse_float(row.get("latitude_deg"))
            lon = parse_float(row.get("longitude_deg"))
            height = parse_float(row.get("ellipsoid_height_m"))
            if height is None:
                height = parse_float(row.get("altitude_m"))
            time_s = parse_float(row.get("sample_time_s")) or parse_float(row.get("gps_tow_s"))

            if lat is None or lon is None:
                continue
            if abs(lat) < 1e-12 and abs(lon) < 1e-12:
                continue
            if height is None:
                height = 0.0

            points.append(TrackPoint(lat_deg=lat, lon_deg=lon, height_m=height, time_s=time_s))

    return points


def latest_file(pattern: str) -> Optional[str]:
    matches = glob.glob(pattern)
    if not matches:
        return None
    return max(matches, key=os.path.getmtime)


def matching_cv7_gps_file(ekf_path: str) -> Optional[str]:
    base = os.path.basename(ekf_path)
    marker = "_ekf_fused_"
    if marker not in base:
        return None
    candidate = os.path.join(os.path.dirname(ekf_path), base.replace(marker, "_gps_raw_"))
    return candidate if os.path.exists(candidate) else None


def default_external_gps_file(ekf_path: str) -> Optional[str]:
    candidate = os.path.join(os.path.dirname(ekf_path), "gps_raw.csv")
    return candidate if os.path.exists(candidate) else None


def choose_reference(ekf_points: List[TrackPoint], gps_points: List[TrackPoint]) -> TrackPoint:
    if ekf_points:
        return ekf_points[0]
    if gps_points:
        return gps_points[0]
    raise SystemExit("No valid EKF or GPS position points found.")


def to_local(points: Iterable[TrackPoint], reference: TrackPoint) -> List[LocalPoint]:
    ref_lat_rad = math.radians(reference.lat_deg)
    cos_lat = math.cos(ref_lat_rad)
    local_points: List[LocalPoint] = []

    for point in points:
        east = math.radians(point.lon_deg - reference.lon_deg) * EARTH_RADIUS_M * cos_lat
        north = math.radians(point.lat_deg - reference.lat_deg) * EARTH_RADIUS_M
        height = point.height_m - reference.height_m
        local_points.append(LocalPoint(east_m=east, north_m=north, height_m=height, time_s=point.time_s))

    return local_points


def downsample(points: List[LocalPoint], max_points: int) -> List[LocalPoint]:
    if max_points <= 0 or len(points) <= max_points:
        return points
    step = math.ceil(len(points) / max_points)
    return points[::step]


def range_text(values: List[float], unit: str) -> str:
    if not values:
        return f"0 {unit}"
    return f"{min(values):.3f} to {max(values):.3f} {unit}"


def plot_2d_points(
    ekf_local: List[LocalPoint],
    gps_local: List[LocalPoint],
    ekf_count: int,
    gps_count: int,
    max_plot_points: int,
) -> None:
    ekf_plot = downsample(ekf_local, max_plot_points)
    gps_plot = downsample(gps_local, max_plot_points)

    fig, ax = plt.subplots(figsize=(9, 7))

    if ekf_plot:
        ax.plot(
            [p.east_m for p in ekf_plot],
            [p.north_m for p in ekf_plot],
            linestyle="None",
            marker=".",
            markersize=2.5,
            color=IMU_EKF_COLOR,
            label=f"IMU/CV7 EKF fused - blue ({ekf_count} points)",
        )
        ax.plot(
            [ekf_plot[0].east_m],
            [ekf_plot[0].north_m],
            linestyle="None",
            marker="o",
            markersize=7,
            color=IMU_EKF_COLOR,
            markeredgecolor=START_EDGE_COLOR,
            label="IMU/CV7 EKF start",
        )
        ax.plot(
            [ekf_plot[-1].east_m],
            [ekf_plot[-1].north_m],
            linestyle="None",
            marker="x",
            markersize=8,
            color=IMU_EKF_COLOR,
            label="IMU/CV7 EKF end",
        )

    if gps_plot:
        ax.plot(
            [p.east_m for p in gps_plot],
            [p.north_m for p in gps_plot],
            linestyle="None",
            marker=".",
            markersize=4,
            color=GPS_RAW_COLOR,
            alpha=0.75,
            label=f"GPS raw - orange ({gps_count} points)",
        )

    ax.set_title(
        f"2D Points | Blue: IMU/CV7 EKF ({ekf_count}) | Orange: GPS raw ({gps_count})"
    )
    ax.set_xlabel("East from first valid point (m)")
    ax.set_ylabel("North from first valid point (m)")
    ax.axis("equal")
    ax.grid(True, linestyle="--", linewidth=0.5, alpha=0.5)
    ax.legend(loc="best")
    fig.tight_layout()


def plot_3d_points(
    ekf_local: List[LocalPoint],
    gps_local: List[LocalPoint],
    ekf_count: int,
    gps_count: int,
    max_plot_points: int,
) -> None:
    ekf_plot = downsample(ekf_local, max_plot_points)
    gps_plot = downsample(gps_local, max_plot_points)
    heights = [p.height_m for p in ekf_local] + [p.height_m for p in gps_local]

    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection="3d")

    if ekf_plot:
        ax.plot(
            [p.east_m for p in ekf_plot],
            [p.north_m for p in ekf_plot],
            [p.height_m for p in ekf_plot],
            linestyle="None",
            marker=".",
            markersize=2.5,
            color=IMU_EKF_COLOR,
            label=f"IMU/CV7 EKF fused - blue ({ekf_count} points)",
        )
        ax.plot(
            [ekf_plot[0].east_m],
            [ekf_plot[0].north_m],
            [ekf_plot[0].height_m],
            linestyle="None",
            marker="o",
            markersize=7,
            color=IMU_EKF_COLOR,
            markeredgecolor=START_EDGE_COLOR,
            label="IMU/CV7 EKF start",
        )
        ax.plot(
            [ekf_plot[-1].east_m],
            [ekf_plot[-1].north_m],
            [ekf_plot[-1].height_m],
            linestyle="None",
            marker="x",
            markersize=8,
            color=IMU_EKF_COLOR,
            label="IMU/CV7 EKF end",
        )

    if gps_plot:
        ax.plot(
            [p.east_m for p in gps_plot],
            [p.north_m for p in gps_plot],
            [p.height_m for p in gps_plot],
            linestyle="None",
            marker=".",
            markersize=4,
            color=GPS_RAW_COLOR,
            alpha=0.75,
            label=f"GPS raw - orange ({gps_count} points)",
        )

    ax.set_title(
        f"3D Points | Blue: IMU/CV7 EKF ({ekf_count}) | Orange: GPS raw ({gps_count})\n"
        f"Relative height range: {range_text(heights, 'm')}"
    )
    ax.set_xlabel("East (m)")
    ax.set_ylabel("North (m)")
    ax.set_zlabel("Height from first valid point (m)")
    ax.legend(loc="best")
    fig.tight_layout()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot CV7 EKF/GPS CSV output as interactive point plots.")
    parser.add_argument("--ekf-csv", help="Path to cv7_ekf_fused_*.csv. Defaults to newest file in IMU_EKF.")
    parser.add_argument("--gps-csv", help="Path to cv7_gps_raw_*.csv or gps_raw.csv. Defaults to the matching CV7 GPS CSV if available.")
    parser.add_argument("--max-plot-points", type=int, default=100000, help="Downsample plotted points above this count. 0 disables downsampling.")
    parser.add_argument("--include-invalid", action="store_true", help="Include EKF rows where position_valid is not 1.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    ekf_csv = args.ekf_csv or latest_file(os.path.join(SCRIPT_DIR, "cv7_ekf_fused_*.csv"))
    if not ekf_csv:
        raise SystemExit("No cv7_ekf_fused_*.csv file found. Provide one with --ekf-csv.")

    gps_csv = args.gps_csv
    if gps_csv is None:
        gps_csv = matching_cv7_gps_file(ekf_csv) or default_external_gps_file(ekf_csv)
        if gps_csv is None:
            gps_csv = latest_file(os.path.join(os.path.dirname(ekf_csv), "cv7_gps_raw_*.csv"))

    ekf_points = read_track_csv(ekf_csv, require_position_valid=not args.include_invalid)
    gps_points = read_track_csv(gps_csv, require_position_valid=False) if gps_csv else []
    reference = choose_reference(ekf_points, gps_points)
    ekf_local = to_local(ekf_points, reference)
    gps_local = to_local(gps_points, reference)

    print(f"EKF CSV      : {ekf_csv}")
    print(f"GPS CSV      : {gps_csv or 'not found'}")
    print(f"EKF points   : {len(ekf_points)}")
    print(f"GPS points   : {len(gps_points)}")
    print("Plot colors  : blue = IMU/CV7 EKF fused, orange = GPS raw")
    print("Opening matplotlib windows. Close the plot windows to finish.")

    plot_2d_points(
        ekf_local=ekf_local,
        gps_local=gps_local,
        ekf_count=len(ekf_points),
        gps_count=len(gps_points),
        max_plot_points=args.max_plot_points,
    )
    plot_3d_points(
        ekf_local=ekf_local,
        gps_local=gps_local,
        ekf_count=len(ekf_points),
        gps_count=len(gps_points),
        max_plot_points=args.max_plot_points,
    )

    plt.show()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
