[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

monitor_speed = 115200
monitor_eol = LF

build_flags = 
    -std=gnu++14
    -Wall
    -O2
    -Ilib/mip_sdk/src
    -DMICROSTRAIN_PLATFORM_EMBEDDED=1
    -DMIP_USE_EXTRAS=0

lib_deps = file://lib/mip_sdk